import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Provider";
import NavBar from "@/components/navbar/Navbar";
import { AuthProvider } from "../contexts/AuthContext";
import dynamic from "next/dynamic";
import { GlobalModalProvider } from "@/contexts/GlobalModalContext";
import MobileMenu from "@/components/navbar/MobileMenu";

const inter = Inter({ subsets: ["latin"] });

const ClientSideLayout = dynamic(() => import("@/components/ClientSideLayout"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <GlobalModalProvider>
              <ClientSideLayout>
                <Toaster position="top-center" />
                {children}
                <MobileMenu />
              </ClientSideLayout>
            </GlobalModalProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
